language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_install:
  - composer self-update

install:
  - composer install --prefer-dist
  - cd Tests/Functional/app && composer install --prefer-dist && cd ../../..

script:
  - composer test
